[tool.pylint.messages_control]
max-line-length = 120
disable = [
    "invalid-name",
    "missing-docstring",
    "too-many-arguments",
]

[tool.yapf]
based_on_style = "google"
column_limit = 120

[tool.pyright]
include = ["src"]
exclude = []
ignore = []
defineConstant = {}
venv = "~/.pyenv/versions/torch/"

reportMissingImports = true
reportMissingTypeStubs = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportIncompatibleMethodOverride = false

pythonVersion = "3.10"
pythonPlatform = "Linux"

executionEnvironments = []
