[tool.yapf]
column_limit = 120

[tool.isort]
py_version=39
line_length = 120

[tool.ruff]
line-length = 120
ignore = [
    "E731"
]

[tool.pyright]
include = ["src"]
exclude = []
ignore = []
defineConstant = {}
venv = "~/.pyenv/versions/torch/"

reportMissingImports = true
reportMissingTypeStubs = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportIncompatibleMethodOverride = false

pythonVersion = "3.10"
pythonPlatform = "Linux"

executionEnvironments = []
