[tool.yapf]
column_limit = 120

[tool.isort]
py_version=39
line_length = 120

[tool.ruff]
line-length = 120
ignore = [
    "E731"
]

[tool.pyright]
include = ["src", "tests"]
exclude = []
ignore = []
defineConstant = {}

reportMissingImports = true
reportMissingTypeStubs = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportIncompatibleMethodOverride = true

pythonVersion = "3.10"
pythonPlatform = "Linux"

executionEnvironments = []
